config/routes.rb
Play::Application.routes.draw do

  get "account" => 'account#show'
  get "account/token" => 'account#token'
  get "search" => 'songs#search'
  get "artists/:artist_name/songs/:title" => 'songs#show', :as => 'song', :constraints => { :title => /[^\/]*/ }
  get "artists/:artist_name/albums/:name" => 'albums#show', :as => 'album', :constraints => { :name => /[^\/]*/ }
  get "artists/:artist_name/songs" => 'artists#songs', :as => 'artist_songs'
  get "artists/:artist_name" => 'artists#show', :as => 'artist', :constraints => { :artist_name => /[^\/]*/ }
  get "images/art/:id.png" => 'images#art'

  get 'artists/:artist_name/albums/:name/download' => 'albums#download', :as => 'album_download'
  get 'songs/download/*path' => 'songs#download', :format => false, :as => 'song_download'
  post 'songs' => 'songs#create'

  get ':login/likes' => 'likes#index'

  resources :likes do
  end

  resources :queue do
  end

  scope '/likes' do
    delete ''          => 'likes#destroy'
  end

  scope '/queue' do
    delete ''          => 'queue#destroy'
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure'         => 'sessions#failure'
  get '/logout'               => 'sessions#logout'

  namespace :api do
    get "/users" => 'users#index', :as => 'users'
    get "/users/:login" => 'users#show', :as => 'user'
    get "/users/:login/likes" => 'users#likes', :as => 'likes_user'

    get "/artists" => 'artists#index', :as => 'artists'
    get "/artists/:artist_name" => 'artists#show', :as => 'artist', :constraints => { :artist_name => /[^\/]*/ }

    get "/artists/:artist_name/albums" => 'albums#index', :as => 'artist_albums'
    get "/artists/:artist_name/albums/:album_name" => 'albums#show', :as => 'artist_album', :constraints => { :album_name => /[^\/]*/ }
    get "/artists/:artist_name/albums/:album_name/download" => 'albums#download', :as => 'download_artist_album'

    get "/artists/:artist_name/songs/:song_name" => 'songs#show', :as => 'song', :constraints => { :song_name => /[^\/]*/ }
    get "/artists/:artist_name/songs/:song_name/download" => 'songs#download', :as => 'download_song'
    put "/artists/:artist_name/songs/:song_name/like" => 'songs#like', :as => 'like_song'
    put "/artists/:artist_name/songs/:song_name/unlike" => 'songs#unlike', :as => 'unlike_song'

    post "/play" => 'controls#play', :as => 'play'
    post "/pause" => 'controls#pause', :as => 'pause'
    post "/next" => 'controls#next', :as => 'next'

    get "/speakers" => 'speakers#index', :as => 'speakers'
    post "/speakers/:speaker_name/volume" => 'speakers#update_volume', :as => 'update_volume_speaker'
    post "/speakers/:speaker_name/mute" => 'speakers#mute', :as => 'mute_speaker'
    post "/speakers/:speaker_name/unmute" => 'speakers#unmute', :as => 'unmute_speaker'
    post "/speakers/:speaker_name/reset" => 'speakers#reset', :as => 'reset_speaker'

    get  "/now_playing" => 'queue#now_playing', :as => 'now_playing'
    post "/now_playing" => 'queue#like_now_playing', :as => 'like_now_playing'
    get  "/queue" => 'queue#list', :as => 'queue'
    post "/queue/add" => 'queue#add', :as => 'add_queue'
    post "/queue/remove" => 'queue#remove', :as => 'remove_queue'
    post "/queue/clear" => 'queue#clear', :as => 'clear_queue'
    post "/queue/stars" => 'queue#stars'

    get "/stream" => 'system#stream', :as => 'stream'

    get "/" => "base#test"
  end

  root :to => 'queue#index'

  get '/:login' => 'users#show'
  get '/:login/history' => 'users#history'

end

app/models/user.rb
module Play

  # The User does things with Play. These are usually employees who try to
  # request songs to be played, but usually request crap like Garth Brooks.
  #
  # redis:
  #
  #   play:users                - A Set of all user IDs.
  #   play:users:#{login}:email - The String email for the given `login`.
  #   play:users:#{login}:token - The String token for the given `login`.
  #   play:users:#{login}:stars - A Set of all Song `permanent_id`s that have
  #                               been starred by `login`.
  #   play:users:#{token}:login - The String login for the given `token`.
  class User

    # The redis key to stash User data.
    KEY = 'play:users'

    # Public: The username of the user's GitHub account.
    attr_accessor :login

    # Public: The public email address listed on GitHub.
    attr_accessor :email

    # Public: The token used to auth with Play from a client.
    attr_accessor :token

    # Public: Initializes a User.
    #
    # login - The String login of their GitHub account.
    # email - The String email address of their GitHub account.
    # token - The String used to auth with Play from a client.
    #
    # Returns the User.
    def initialize(login,email,token=nil)
      @login = login.downcase
      @email = email
      @token = token
    end

    # Public: Create a User.
    #
    # login - The String login of their GitHub account.
    # email - The String email address of their GitHub account.
    #
    # Returns the User.
    def self.create(login,email)
      User.new(login,email).save
    end

    # Public: Return all users.
    #
    # Returns the User.
    def self.all
      logins = $redis.smembers KEY
      logins.map{|login| find(login)}
    end


    # Public: Finds a User.
    #
    # login - The String login.
    #
    # Returns the User, nil if no User found.
    def self.find(login)
      login.downcase!
      return nil if !$redis.sismember(KEY, login)
      email = $redis.get "#{KEY}:#{login}:email"
      token = $redis.get "#{KEY}:#{login}:token"

      User.new(login,email,token)
    end

    # Public: Finds a User by token.
    #
    # token - The String auth token.
    #
    # Returns the User, nil if no User found.
    def self.find_by_token(token)
      return nil if !login = $redis.get("#{KEY}:#{token}:login")
      self.find(login)
    end

    # Public: Saves the User.
    #
    # Returns itself.
    def save
      $redis.sadd KEY, login
      save_email
      save_token
      self
    end

    # Public: Saves the email.
    #
    # Returns bool.
    def save_email
      $redis.set  "#{KEY}:#{login}:email", email
    end

    # Public: Saves the token.
    #
    # Returns bool.
    def save_token
      self.token ||= Digest::MD5.hexdigest(login + Time.now.to_i.to_s)[0..5]
      $redis.set  "#{KEY}:#{login}:token", token
      $redis.set  "#{KEY}:#{token}:login", login
    end

    # Public: The MD5 hash of the user's email account. Used for showing their
    # Gravatar.
    #
    # Returns the String MD5 hash.
    def gravatar_id
      Digest::MD5.hexdigest(email) if email
    end

    # Public: A User's saved songs.
    #
    # Returns an Array of Songs.
    def stars
      stars = $redis.smembers("#{KEY}:#{login}:stars")
      stars.map do |id|
        Song.find(id)
      end
    end

    # Public: Did this user star this song?
    #
    # song - The Song.
    #
    # Returns a Boolean value.
    def starred?(song)
      $redis.smembers("#{KEY}:#{login}:stars").include?(song.id)
    end

    # Public: Stars a song. Likes a song. Saves a song. Updates global stat counters for the song.
    #
    # song - The Song to star.
    #
    # Returns true when saved.
    def star(song)
      $redis.sadd("#{KEY}:#{login}:stars",song.id)
      History.star_song(song)
      true
    end

    # Public: Removes a star.
    #
    # song - The Song to unstar.
    #
    # Returns true when saved.
    def unstar(song)
      $redis.srem("#{KEY}:#{login}:stars",song.id)
      History.unstar_song(song)
      true
    end

  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::BaseController

  def index
    users = User.all
    deliver_json(200, {:users => users.collect(&:to_hash)})
  end

  def show
    user = User.find_by_login(params[:login])
    deliver_json(200, user.to_hash)
  end

  def likes
    current_page = params[:page] || 1

    user = User.find_by_login(params[:login])
    likes = user.liked_songs(current_page)

    deliver_json(200, songs_response(likes, current_user).merge(:total_entries => user.likes.count))
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by_login(params[:login])
    return render_404 if !@user

    @plays = @user.favorite_songs
  end

  def history
    @user = User.find_by_login(params[:login])
    return render_404 if !@user

    @songs = @user.plays
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/history.html.erb
<div id="queue">
  <div class="heading">
    <span class="title"><%= @user.login %></span>
    <div class="tabs">
      <a class="<%= 'active' if controller.action_name == 'show' %>" href="/<%= @user.login %>">Profile</a>
      <a class="<%= 'active' if controller.action_name == 'history' %>" href="/<%= @user.login %>/history">History</a>
      <a class="<%= 'active' if controller.controller_name == 'likes' %>" href="/<%= @user.login %>/likes">Likes</a>
    </div>
  </div>

  <%= render :partial => 'shared/song', :collection => @songs %>
</div>

app/views/users/show.html.erb
<div id="queue">
  <div class="heading">
    <span class="title"><%= @user.login %></span>
    <div class="tabs">
      <a class="<%= 'active' if controller.action_name == 'show' %>" href="/<%= @user.login %>">Profile</a>
      <a class="<%= 'active' if controller.action_name == 'history' %>" href="/<%= @user.login %>/history">History</a>
      <a class="<%= 'active' if controller.controller_name == 'likes' %>" href="/<%= @user.login %>/likes">Likes</a>
    </div>
  </div>

  <% if @user == current_user %>
  <div id="name">
    <h4>Your Auth Token: <strong><%= @user.token %></strong></h4>
  </div>
  <% end %>

  <h4>Favorite Songs</h4>
  <% if @plays.present? %>
    <table class="tracklist">
      <tr>
        <th colspan="2">Track</th>
        <th colspan="1">Album</th>
        <th colspan="6">Plays</th>
      </tr>
      <% @plays.each do |play| %>
        <% track = play.song %>
          <tr class="track" data-path="<%= track.path %>" data-channel="<%= current_channel.id %>">
            <td class="number"><%= @plays.index(play) + 1 %>.</td>
            <td class="title"><%= link_to track.title, song_path(track.artist, track) %></td>
            <td class="album"><%= link_to track.album_name, album_path(track.artist, track.album), :class => "album" %></td>

            <td class="duration"><%= play.playcount %></td>
            <td class="queue"><%= render :partial => 'shared/queue', :locals => { :song => track } %></td>
            <td class="like"><%= render :partial => 'shared/like', :locals => { :song => track } %></td>
            <td class="download">
              <a href="/download/<%= track.path %>"><span class="icon-cloud-download"></span></a>
            </td>

          </tr>
      <% end %>
    </table>
  <% else %>
    <div class="heading">
      <p><%= @user.login %> doesn't have any favorite songs yet. What a killjoy.</p>
    </div>
  <% end %>
</div>