config/routes.rb
Play::Application.routes.draw do

  get "account" => 'account#show'
  get "account/token" => 'account#token'
  get "search" => 'songs#search'
  get "artists/:artist_name/songs/:title" => 'songs#show', :as => 'song', :constraints => { :title => /[^\/]*/ }
  get "artists/:artist_name/albums/:name" => 'albums#show', :as => 'album', :constraints => { :name => /[^\/]*/ }
  get "artists/:artist_name/songs" => 'artists#songs', :as => 'artist_songs'
  get "artists/:artist_name" => 'artists#show', :as => 'artist', :constraints => { :artist_name => /[^\/]*/ }
  get "images/art/:id.png" => 'images#art'

  get 'artists/:artist_name/albums/:name/download' => 'albums#download', :as => 'album_download'
  get 'songs/download/*path' => 'songs#download', :format => false, :as => 'song_download'
  post 'songs' => 'songs#create'

  get ':login/likes' => 'likes#index'

  resources :likes do
  end

  resources :queue do
  end

  scope '/likes' do
    delete ''          => 'likes#destroy'
  end

  scope '/queue' do
    delete ''          => 'queue#destroy'
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure'         => 'sessions#failure'
  get '/logout'               => 'sessions#logout'

  namespace :api do
    get "/users" => 'users#index', :as => 'users'
    get "/users/:login" => 'users#show', :as => 'user'
    get "/users/:login/likes" => 'users#likes', :as => 'likes_user'

    get "/artists" => 'artists#index', :as => 'artists'
    get "/artists/:artist_name" => 'artists#show', :as => 'artist', :constraints => { :artist_name => /[^\/]*/ }

    get "/artists/:artist_name/albums" => 'albums#index', :as => 'artist_albums'
    get "/artists/:artist_name/albums/:album_name" => 'albums#show', :as => 'artist_album', :constraints => { :album_name => /[^\/]*/ }
    get "/artists/:artist_name/albums/:album_name/download" => 'albums#download', :as => 'download_artist_album'

    get "/artists/:artist_name/songs/:song_name" => 'songs#show', :as => 'song', :constraints => { :song_name => /[^\/]*/ }
    get "/artists/:artist_name/songs/:song_name/download" => 'songs#download', :as => 'download_song'
    put "/artists/:artist_name/songs/:song_name/like" => 'songs#like', :as => 'like_song'
    put "/artists/:artist_name/songs/:song_name/unlike" => 'songs#unlike', :as => 'unlike_song'

    post "/play" => 'controls#play', :as => 'play'
    post "/pause" => 'controls#pause', :as => 'pause'
    post "/next" => 'controls#next', :as => 'next'

    get "/speakers" => 'speakers#index', :as => 'speakers'
    post "/speakers/:speaker_name/volume" => 'speakers#update_volume', :as => 'update_volume_speaker'
    post "/speakers/:speaker_name/mute" => 'speakers#mute', :as => 'mute_speaker'
    post "/speakers/:speaker_name/unmute" => 'speakers#unmute', :as => 'unmute_speaker'
    post "/speakers/:speaker_name/reset" => 'speakers#reset', :as => 'reset_speaker'

    get  "/now_playing" => 'queue#now_playing', :as => 'now_playing'
    post "/now_playing" => 'queue#like_now_playing', :as => 'like_now_playing'
    get  "/queue" => 'queue#list', :as => 'queue'
    post "/queue/add" => 'queue#add', :as => 'add_queue'
    post "/queue/remove" => 'queue#remove', :as => 'remove_queue'
    post "/queue/clear" => 'queue#clear', :as => 'clear_queue'
    post "/queue/stars" => 'queue#stars'

    get "/stream" => 'system#stream', :as => 'stream'

    get "/" => "base#test"
  end

  root :to => 'queue#index'

  get '/:login' => 'users#show'
  get '/:login/history' => 'users#history'

end

app/views/shared/_channel.html.erb
<div class="channel">
  <%= link_to channel_path(channel), :class => 'channel-image' do %>
    <img src="<%= channel.now_playing ? "/images/art/#{channel.now_playing.art_file}" : "/images/art-placeholder.png" %>" width="100" height="100" />
  <% end %>

  <div class="details">
    <h2 class="title">
      <%= link_to channel.name, channel_path(channel) %>
    </h2>
    <div class="meta">
    <% if channel.now_playing %>
      <%= channel.now_playing.artist_name %>
      <% if channel.now_playing.title.present? %>
        <span class="betweener">-</span>
        <%= channel.now_playing.title %>
      <% end %>
    <% end%>
    </div>
  </div>
</div>

app/views/shared/_like.html.erb
<% full = false unless full %>

<% if current_user_likes.map(&:song_path).include?(song.path) %>
  <span class="icon-star unlike octicon"></span> <%= 'Unstar Song' if full %>
<% else %>
  <span class="icon-star-empty like octicon"></span> <%= 'Star Song' if full %>
<% end %>

app/views/shared/_no_music.html.erb
<div class="error">
  <h1>The music server isn't running.</h1>
  <p>Spin it up with <code>script/music start</code>.</p>
</div>

app/views/shared/_nothing_queued.html.erb
<div class="error">
  <h1>Nothing's queued up.</h1>
  <p>Always keep the music playing with <code>script/queue</code>.</p>
</div>

app/views/shared/_queue.html.erb
<% if current_playlist.include?(song) %>
  <span class="icon-remove-sign remove octicon"></span>
<% else %>
  <span class="icon-plus-sign-alt add octicon"></span>
<% end %>

app/views/shared/_sidebar.html.erb
<%
  return if !Play.default_channel
  song = current_channel.queue.first
  return if !song || !flash[:error].blank?
%>
<div id="sidebar">
  <div class="now-playing">
    <%= link_to album_path(song.artist, song.album), :class => 'album-art' do %>
      <img src="/images/art/<%= song.art_file %>" />
    <% end %>

    <div class="now-playing-meta">
      <h2 class="title" title="<%= song.title %>"><%= song.title %></h2>
      <p class="album-info">
        <%= link_to song.artist_name, artist_path(song.artist), :class => 'artist' %> -
        <%= link_to song.album_name, album_path(song.artist, song.album) %>
      </p>
    </div>
    <hr>
    <ul class="now-playing-actions" data-path="<%= song.path %>" data-channel="<%= current_channel.id %>">
      <li><%= render :partial => 'shared/like', :locals => { :song => song, :full => true } %></li>
      <li>
        <%= link_to song_download_path(song) do %>
          <span class="now-playing-action-icon icon-cloud-download"></span> Download Song
        <% end %>
      </li>
    </ul>
  </div>

  <div class="tune-fans">
    <h3>Tune Fans</h3>
    <div class="fans">
      <ul>
      <% likes=song.likes.each do |like| %>
        <li class="fan" data-login="<%= like.user.login %>">
          <a href="/<%= like.user.login %>">
            <img src="//www.gravatar.com/avatar/<%= like.user.gravatar_id %>?s=50" alt="<%= like.user.login %>" />
          </a>
        </li>
      <% end %>

      <% if likes.empty? %>
        <li>No one likes this. Yet.</li>
      <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_song.html.erb
<div class="song" data-path="<%= song.path %>" data-channel="<%= current_channel.id %>">
  <%= link_to album_path(song.artist, song.album), :class => 'album-art' do %>
    <img src="/images/art/<%= song.art_file %>" width="100" height="100" />
  <% end %>

  <%= link_to album_download_path(song.artist ? song.artist.name : 'Unknown Artist', song.album), :class => "album-download", :title => "Download this album" do %>
    <span class="icon-cloud-download"></span>
  <% end %>
  <div class="details">
    <h2 class="title">
      <%= link_to song.title, song_path(song.artist, song) %>
      <span class="duration"> (<%= song.duration %>)</span>
    </h2>

    <div class="meta">
      <%= link_to(song.artist_name, artist_path(song.artist), :class => 'artist') %>

      <% if song.album_name.present? %>
        <span class="betweener">-</span>
        <%= link_to(song.album_name, album_path(song.artist, song.album), :class => 'album') %>
      <% end %>
    </div>
  </div>
  <div class="controls">
    <%= render :partial => 'shared/queue', :locals => {:song => song} %>
    <%= render :partial => 'shared/like', :locals => {:song => song} %>
    <%= link_to song_download_path(song.path) do %>
      <span class="icon-cloud-download"></span></a>
    <% end %>
  </div>
</div>

app/views/shared/_track.html.erb
<tr class="track" data-path="<%= track.path %>" data-channel="<%= current_channel.id %>">
  <td class="number"><%= @songs.index(track) + 1 %>.</td>
  <td class="title"><%= link_to track.title, song_path(track.artist, track) %></td>
  <td class="album"><a href="<%= album_path(track.artist.name, track.album.name) if track.album.name %>" class="album"><%= track.album_name %></a></td>

  <td class="duration"><%= track.duration %></td>
  <td class="download">
    <%= link_to song_download_path(track.path) do %>
      <span class="icon-cloud-download"></span>
    <% end %>
  </td>

  <td class="like"><%= render :partial => 'shared/like', :locals => { :song => track } %></td>
  <td class="queue"><%= render :partial => 'shared/queue', :locals => { :song => track } %></td>
</tr>

app/views/shared/error.html.erb
<div class="error">
  <h1>The day the music stopped: <b>TODAY</b>.</h1>
  <p><%= flash[:error] %></p>
</div>

app/views/shared/no_music.html.erb
<div class="error">
  <h1>The music server isn't running.</h1>
  <p>Spin it up with <code>script/music start</code>.</p>
</div>

app/views/shared/nothing_queued.html.erb
<div class="error">
  <h1>Nothing's queued up.</h1>
  <p>Always keep the music playing with <code>script/queue</code>.</p>
</div>